src/objects/Position__c.object
<CustomObject>
    <description>This object stores information
about the open job positions at our company</description>
    <fields>
        <fullName>Max_Pay__c</fullName>
        <description>Maximum wages</description>
        <inlineHelpText>Maximum wages</inlineHelpText>
        <label>Max Pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Min_Pay__c</fullName>
        <description>minimum pay of the position</description>
        <inlineHelpText>minimum pay of the position</inlineHelpText>
        <label>Min Pay</label>
        <precision>9</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Position</label>
    <nameField>
        <label>Position Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/tan.cls
public class tan {
    public  ID a{get;set;}
     public  Position__c b{get;set;}
       public  String c
      {
        get
          {
      if(c.equals('piku'))
          c='HELLLLLOOOOOOOOOOOOOOOOOOOOOOO';
      if(c == '')
          c='OPPs something went wrong';
          return c;
          }
      set;
      
      }
    
    
    public tan(ApexPages.StandardController controller) 
    {
        a = ApexPages.currentPage().getParameters().get('id');
        b = (Position__c )controller.getRecord();
        c = ApexPages.currentPage().getParameters().get('piku');
    }

public  ID getId()
{
  return a;

}
public  ID getId2()
{
  return b.ID;

}
public  String getId3()
{
  return c;

}
public Double getdiffr()
{
Object a=(Position__c.Max_Pay__c);
Object b=(Position__c.Min_Pay__c);

Decimal c=(Decimal)a;
Decimal d=(Decimal)b;
return (c-d);

}
 


}