src/objects/Recorded_Message__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Recorded Message</relationshipLabel>
        <relationshipName>Recorded_Messages</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>record_message_url__c</fullName>
        <label>Record message Url</label>
        <type>Url</type>
    </fields>
    <label>Recorded Message</label>
    <nameField>
        <label>Recorded Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recorded Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContactstoreurlController.cls
public class ContactstoreurlController {
 
 
 Public String Fromno;
 Public String RecordingUrl;
 public boolean activatepoll {get;set;}

 public ContactstoreurlController(){
   activatepoll = false;
   Fromno = System.currentPageReference().getParameters().get('From').replace('client:','');
   RecordingUrl = System.currentPageReference().getParameters().get('RecordingUrl')+'.mp3';
   system.debug(Fromno +'<======>'+ RecordingUrl );
   if(Fromno != null && Fromno.length()>2)
     activatepoll = true;
  


}

public void inserturl()
{
 Contact con = [SELECT Name FROM Contact WHERE ID =:Fromno LIMIT 1];
 Recorded_Message__c a = new Recorded_Message__c(Contact__c =con.id , record_message_url__c=RecordingUrl);
 insert a;
   
}



}